### ISSUE TITLE
Error happened when opening cmdwin with Neovim inccommand=nosplit

### ISSUE THREAD

**Issue by ghost** [itchyny/vim-parenmatch#5]
`set inccommand=nosplit`と一緒に使い，cmdwinを開くとエラーが出ます

以下のvimrcと一緒に当該リポジトリ内で `nvim -u vimrc` をして確認しています

`nvim -v | head -1` は `NVIM v0.5.0-330-g71ee46acc`

```
let &rtp ..= ',' .. expand('<sfile>:h')

set icm=nosplit
```

---

```
iabc<ESC>
:s/ab<C-f>
```

```
Error detected while processing function parenmatch#update:
line   11:
E171: Missing :endif
E171: Missing :endif
```

(これは `:mes` をすることでエラーが確認できたんですが，普段の自分のvimrcではエラーが出て中断されてしまいます)

---

```
<C-c>
```

```
Error detected while processing function parenmatch#timer_callback[1]..parenmatch#update:
line   11:
E171: Missing :endif
```

cursorwordでも似たようなエラーが出ます https://github.com/itchyny/vim-cursorword/issues/19

**Comment by itchyny** [comment]
![p](https://user-images.githubusercontent.com/375258/73808929-de0a8a80-4814-11ea-84d4-ef8b6cf491c3.gif)
nvim詳しくないんですが0.4.3だとエラー出ませんでした…

**Comment by ghost** [comment]
はい，すみません，Neovimのバグかもしれません，すみません

**Comment by itchyny** [comment]
I reported to https://github.com/neovim/neovim/issues/11818. This is a bug of neovim, not this plugin.
