### ISSUE TITLE
E28: No such highlight group name: ParenMatch

### ISSUE THREAD

**Issue by cs86661** [itchyny/vim-parenmatch#7]
![image](https://user-images.githubusercontent.com/2338762/76163341-2e606980-6180-11ea-94b4-4d3c7d3516f7.png)

Error messages show up when open file that cursor right on any matching parenthesis...

**Comment by itchyny** [comment]
Can you confirm after updating the plugin?

**Comment by cs86661** [comment]
> Can you confirm after updating the plugin?

Yes. It's been the latest version.

**Comment by itchyny** [comment]
I can't reproduce the issue. Please describe the precise steps, minimal vimrc and Vim version.

**Comment by cs86661** [comment]
Windows GVim 8.2.346

```vim
silent call plug#begin()
Plug $VIM.'/vimfiles/Plug/parenmatch'
let g:loaded_matchparen=1
call plug#end()
```

create new file `abc`, and it only contains two characters: `[]`
Open `Command Prompt`, then enter `gvim -u mini_vimrc abc`

![image](https://user-images.githubusercontent.com/2338762/76187212-b8a3de80-620f-11ea-873f-241d515d7138.png)
![image](https://user-images.githubusercontent.com/2338762/76187227-c194b000-620f-11ea-8c5f-a23f23e460e4.png)

**Comment by ghost** [comment]
Nothing to add except I'm getting this too, after first installation today

**Comment by itchyny** [comment]
This issue has been fixed.

**Comment by cs86661** [comment]
> This issue has been fixed.

Thanks. :)
